packages:
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - nestjs-pino
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - msw
  - sqlite3
